# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeltranslation', '0006_auto_20160119_1321'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='fieldtranslation',
            index_together=set([('source_md5',), ('module', 'model', 'object_id', 'lang', 'field', 'is_fuzzy')]),
        ),
    ]
